"""Golden vectors.

For Luhn and IBAN these are externally verifiable (public standards).
For the Saudi National ID variant they are INTERNALLY consistent
round-trip vectors generated by our own check-digit function — they
prove the validator and the generator agree, NOT that the algorithm
matches an authoritative government spec (see REFERENCES.md).
"""
from tabayyan.checksums import (
    iban_mod97_is_valid, luhn_is_valid, saudi_id_check_digit, saudi_id_is_valid,
)


# Luhn — public, externally verifiable test numbers.
def test_luhn_public_vectors():
    valid = ["4111111111111111", "5500005555555559", "79927398713"]
    invalid = ["4111111111111112", "79927398710"]
    for v in valid:
        assert luhn_is_valid(v), v
    for v in invalid:
        assert not luhn_is_valid(v), v


# IBAN — ISO 13616 mod-97; check digits computed by the standard must verify.
def test_iban_mod97_self_consistent():
    # Construct via the standard so the math is externally reproducible.
    from tabayyan.checksums import iban_check_digits
    bban = "80000000608010167519"
    iban = "SA" + iban_check_digits("SA", bban) + bban
    assert len(iban) == 24
    assert iban_mod97_is_valid(iban)
    # mutate one digit -> must fail
    assert not iban_mod97_is_valid(iban[:6] + str((int(iban[6]) + 1) % 10) + iban[7:])


# Saudi National ID — internal round-trip consistency (clearly scoped).
def test_saudi_id_internal_roundtrip_vectors():
    prefixes = ["100000000", "123456789", "200000000", "298765432"]
    for pre in prefixes:
        full = pre + str(saudi_id_check_digit(pre))
        assert saudi_id_is_valid(full), full
        assert not saudi_id_is_valid(full[:-1] + str((int(full[-1]) + 1) % 10))
